import React from "react";

//! Look through `Class-Stateful-Lifecycle-Comp.js` to under stand the basic syntax of class-based components

class componentDidUpdateTest extends React.Component {
    constructor(props) {
        super(props); 
        
        this.state = {
            count: 0,
        }
    }

    incrementCount = () => {
      this.setState((state, props) => ({
        count: state.count + 1,
      }));
    }

    // This lifecycle method is called when the props/state of the component has been updated, and the corresponding re-render has occurred. This is confirmed by the sequence of logs generated by the render() method and this one.
    componentDidUpdate(prevProps, prevState) {
        console.log("componentDidUpdate lifecycle method");

        console.log(`Last count value: ${prevState.count}\nCurrent count value: ${this.state.count}`);
    }


    render() {
        console.log("Render");

        return (<div>
            <p>Count: {this.state.count}</p>            
            <button onClick={() => this.incrementCount()}>Increment count</button>
        </div>)
    }
    
}

export default componentDidUpdateTest